Repository boyzwhocried/payroll-service-system-fe, pull requests merged in 2024-05, with the labels that each got.

#1 Integrate Login Functionality from login to dev Branch
  .vscode/settings.json
  src/app/app.routes.ts
  src/app/pages/login/login.component.css
  src/app/pages/login/login.component.html
  src/app/pages/login/login.component.spec.ts
  src/app/pages/login/login.component.ts
  src/assets/images/login/login.png
Labels: enhancement

#11 Merge feat into staging
  src/app/app.routes.ts
  src/app/pages/users/new/new.users.component.html
  src/app/pages/users/new/new.users.component.ts
  src/app/pages/users/user.module.ts
  src/app/pages/users/user.routing.ts
  src/assets/images/user/create-user.svg
Labels: enhancement

#20 Merge Dev into Staging
  .vscode/settings.json
  src/app/app.routes.ts
  src/app/models/dto/company/company.req.dto.ts
  src/app/models/dto/company/company.res.dto.ts
  src/app/pages/companies/companies.component.css
  src/app/pages/companies/companies.component.html
  src/app/pages/companies/companies.component.spec.ts
  src/app/pages/companies/companies.component.ts
  src/app/pages/users/users.component.ts
Labels: enhancement

#25 Merge Dev into Staging
  .vscode/settings.json
  src/app/app.component.ts
  src/app/dto/delete.res.dto.ts
  src/app/dto/file/image.res.dto.ts
  src/app/dto/insert.res.dto.ts
  src/app/dto/payroll/payroll.res.dto.ts
  src/app/dto/update.res.dto.ts
  src/app/pages/companies/companies.component.ts
  src/app/pages/login/login.component.ts
  src/app/pages/schedules/schedules.component.ts
  src/app/pages/users/new/new.users.component.css
  src/app/pages/users/new/new.users.component.html
  src/app/pages/users/new/new.users.component.ts
  src/app/pages/users/users.component.html
  src/app/pages/users/users.component.ts
  src/app/services/auth/auth.service.ts
  src/app/services/base/base.service.ts
  src/app/services/file/file.service.spec.ts
  src/app/services/file/file.service.ts
  src/app/services/payroll.service.ts
  src/app/services/role/role.service.spec.ts
  src/app/services/role/role.service.ts
  src/app/services/user/user.service.ts
Labels: enhancement

#27 Request Merge Companies to Staging
  src/app/components/navbar/navbar.component.ts
  src/app/dto/company/update-company.req.dto.ts
  src/app/pages/companies/companies.component.html
  src/app/pages/companies/companies.component.ts
  src/app/services/base/base.service.ts
  src/app/services/company/company.service.spec.ts
  src/app/services/company/company.service.ts
Labels: documentation

#28 Enhance Management Features and Table Functionality
  src/app/pages/companies/companies.component.css
  src/app/pages/companies/companies.component.html
  src/app/pages/companies/companies.component.ts
  src/app/pages/users/users.component.html
  src/app/pages/users/users.component.ts
  src/app/services/company/company.service.ts
Labels: documentation, enhancement

#29 Request Merge Client Assign to Staging
  src/app/app.routes.ts
  src/app/dto/user/client-list.res.dto.ts
  src/app/dto/user/client.res.dto.ts
  src/app/dto/user/ps-list.res.dto.ts
  src/app/pages/assign/assign-client/assign-client.component.html
  src/app/pages/assign/assign-client/assign-client.component.ts
  src/app/pages/assign/assign.component.html
  src/app/pages/assign/assign.component.ts
  src/app/services/assign/assign.service.spec.ts
  src/app/services/assign/assign.service.ts
  src/app/services/company/company.service.spec.ts
Labels: documentation, enhancement

#30 Request Merge Feat/schedules to Staging
  src/app/app.routes.ts
  src/app/constants/schedule-request-types.constant.ts
  src/app/dto/payroll/payroll.res.dto.ts
  src/app/dto/schedule/schedule.res.dto.ts
  src/app/pages/companies/companies.component.ts
  src/app/pages/schedules/client-schedules/client-schedules.component.html
  src/app/pages/schedules/client-schedules/client-schedules.component.ts
  src/app/pages/schedules/create-schedule/create-schedule.component.html
  src/app/pages/schedules/create-schedule/create-schedule.component.ts
  src/app/pages/schedules/schedules.component.html
  src/app/pages/schedules/schedules.component.ts
  src/app/pages/users/new/new.users.component.ts
  src/app/services/payroll.service.ts
  src/env/environment.prod.ts
Labels: bug, documentation, enhancement

#32 Request Merge Notification Feat to Staging
  src/app/app.routes.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.ts
  src/app/dto/general-response/delete.res.dto.ts
  src/app/dto/insert.res.dto.ts
  src/app/dto/notification/notification.res.dto.ts
  src/app/dto/update.res.dto.ts
  src/app/dto/user/password.req.dto.ts
  src/app/dto/user/profile.res.dto.ts
  src/app/dto/user/update-user.req.dto.ts
  src/app/pages/change-password/change-password.component.html
  src/app/pages/change-password/change-password.component.ts
  src/app/pages/notification/notification.component.css
  src/app/pages/notification/notification.component.html
  src/app/pages/notification/notification.component.ts
  src/app/pages/profile/profile.component.html
  src/app/pages/profile/profile.component.ts
  src/app/pages/users/new/new.users.component.html
  src/app/pages/users/new/new.users.component.ts
  src/app/services/assign/assign.service.ts
  src/app/services/base/base.service.ts
  src/app/services/notification/notification.service.ts
  src/app/services/user/user.service.ts
Labels: documentation, enhancement

#33 Feat/schedules
  src/app/app.routes.ts
  src/app/dto/document/old-document.req.dto.ts
  src/app/dto/document/update-document-schedule.req.dto.ts
  src/app/dto/document/upload-document.req.dto.ts
  src/app/dto/schedule/reschedule.req.dto.ts
  src/app/dto/schedule/schedule.res.dto.ts
  src/app/pages/companies/companies.component.ts
  src/app/pages/schedules/client-schedules/client-schedules.component.html
  src/app/pages/schedules/client-schedules/client-schedules.component.ts
  src/app/pages/schedules/create-schedule/create-schedule.component.html
  src/app/pages/schedules/create-schedule/create-schedule.component.ts
  src/app/pages/schedules/reschedule/reschedule.component.css
  src/app/pages/schedules/reschedule/reschedule.component.html
  src/app/pages/schedules/reschedule/reschedule.component.spec.ts
  src/app/pages/schedules/reschedule/reschedule.component.ts
  src/app/pages/schedules/schedules.component.html
  src/app/pages/schedules/schedules.component.ts
  src/app/pages/users/new/new.users.component.ts
  src/app/pages/users/users.component.ts
  src/app/services/document.service.ts
  src/app/services/payroll.service.ts
Labels: documentation, enhancement

#34 Merge feat/pages-validation into staging
  src/app/app.routes.ts
  src/app/pages/not-found copy/forbidden.component.css
  src/app/pages/not-found copy/forbidden.component.html
  src/app/pages/not-found copy/forbidden.component.spec.ts
  src/app/pages/not-found copy/forbidden.component.ts
  src/app/pages/not-found/not-found.component.css
  src/app/pages/not-found/not-found.component.html
  src/app/pages/not-found/not-found.component.spec.ts
  src/app/pages/not-found/not-found.component.ts
  src/app/pages/schedules/client-schedules/client-schedules.component.html
  src/app/pages/schedules/schedules.component.html
  src/app/validations/role.validations.ts
  src/assets/images/forbidden/403-Error-Forbidden.svg
  src/assets/images/not-found/404-error.svg
Labels: documentation, enhancement
